// Seed data so `bun run dev` and SSG builds work without a live daemon.
// Also drives the screenshots in the docs site.

import type {
  Claim,
  ClaimsResponse,
  ClusterMode,
  GraphEdge,
  GraphNode,
  HealthResponse,
  NeighborsQuery,
  NeighborsResponse,
  NodeDetail,
  NodeId,
  NodeKind,
  SearchResponse,
  StatsResponse,
} from "./types";

const NAMES: ReadonlyArray<{ id: string; name: string; kind: NodeKind; file: string }> = [
  { id: "auth/login_handler", name: "loginHandler", kind: "function", file: "src/auth/login.ts" },
  { id: "auth/validate_session", name: "validateSession", kind: "function", file: "src/auth/session.ts" },
  { id: "auth/hash_password", name: "hashPassword", kind: "function", file: "src/auth/crypto.ts" },
  { id: "auth/create_session_cookie", name: "createSessionCookie", kind: "function", file: "src/auth/session.ts" },
  { id: "auth/admin_login_handler", name: "adminLoginHandler", kind: "function", file: "src/auth/admin.ts" },
  { id: "api/router", name: "apiRouter", kind: "function", file: "src/api/router.ts" },
  { id: "db/users_repo", name: "UsersRepo", kind: "class", file: "src/db/users.ts" },
  { id: "db/connection", name: "openConnection", kind: "function", file: "src/db/conn.ts" },
  { id: "mail/send_login_alert", name: "sendLoginAlert", kind: "function", file: "src/mail/alerts.ts" },
  { id: "util/logger", name: "logger", kind: "module", file: "src/util/log.ts" },
];

const EDGES: ReadonlyArray<[string, string, GraphEdge["kind"], number]> = [
  ["api/router", "auth/login_handler", "static_call", 1],
  ["api/router", "auth/admin_login_handler", "static_call", 1],
  ["auth/login_handler", "auth/validate_session", "trace_call", 47],
  ["auth/login_handler", "auth/hash_password", "trace_call", 47],
  ["auth/login_handler", "auth/create_session_cookie", "trace_call", 47],
  ["auth/login_handler", "db/users_repo", "static_call", 1],
  ["auth/login_handler", "mail/send_login_alert", "trace_call", 12],
  ["auth/admin_login_handler", "auth/validate_session", "trace_call", 3],
  ["auth/admin_login_handler", "auth/hash_password", "trace_call", 3],
  ["auth/validate_session", "util/logger", "static_call", 1],
  ["auth/hash_password", "util/logger", "static_call", 1],
  ["db/users_repo", "db/connection", "trace_call", 47],
  ["db/users_repo", "util/logger", "static_call", 1],
  ["db/connection", "util/logger", "static_call", 1],
];

const BODY: Record<string, string> = {
  "auth/login_handler": `# loginHandler(req, res)

Validates user credentials against the database, issues a session token,
and sets the auth cookie. Calls validate_session for token verification
and hash_password for credential checking.

## Observed callers (from traces)
- api/router (47 invocations)
- auth/admin_login_handler (3 invocations)

## Observed callees (from traces)
- auth/validate_session (47 invocations)
- auth/hash_password (47 invocations)
- auth/create_session_cookie (47 invocations)
`,
};

function bodyFor(id: string, name: string, kind: NodeKind): string {
  return BODY[id] ?? `# ${name}\n\nA ${kind} indexed by Hayvenhurst.\n\n_Summary will be generated by the local Tier-3 model after first ingest._\n`;
}

export function mockHealth(): HealthResponse {
  return { ok: true, version: "0.0.1-dev", native_version: "0.0.1-dev" };
}

export function mockStats(): StatsResponse {
  return {
    nodes: NAMES.length,
    edges: EDGES.length,
    traces: EDGES.reduce((a, [, , k, w]) => (k === "trace_call" ? a + w : a), 0),
    last_ingest: new Date(Date.now() - 90_000).toISOString(),
    peers: [
      { id: "self", url: "localhost:7777", status: "ok", last_sync: new Date().toISOString() },
    ],
    recent_activity: [
      { ts: new Date(Date.now() - 90_000).toISOString(), kind: "ingest", summary: "Incremental ingest: 3 nodes touched" },
      { ts: new Date(Date.now() - 600_000).toISOString(), kind: "trace", summary: "47 trace observations from pytest run" },
      { ts: new Date(Date.now() - 3_600_000).toISOString(), kind: "claim", summary: "agent_3 claimed auth/login_handler" },
    ],
  };
}

export function mockNode(id: NodeId): NodeDetail {
  const found = NAMES.find((n) => n.id === id);
  const meta = found ?? { id, name: id.split("/").pop() ?? id, kind: "unknown" as NodeKind, file: "(unknown)" };
  const callers = EDGES.filter(([, dst]) => dst === id).map(([src, , , w]) => ({ id: src, name: NAMES.find((n) => n.id === src)?.name ?? src, weight: w }));
  const callees = EDGES.filter(([src]) => src === id).map(([, dst, , w]) => ({ id: dst, name: NAMES.find((n) => n.id === dst)?.name ?? dst, weight: w }));
  return {
    id,
    kind: meta.kind,
    language: "typescript",
    file: meta.file,
    range: { start: 1, end: 42 },
    body_md: bodyFor(id, meta.name, meta.kind),
    callers,
    callees,
  };
}

export function mockSearch(q: string): SearchResponse {
  const ql = q.trim().toLowerCase();
  if (!ql) return { hits: [] };
  const hits = NAMES.filter(
    (n) => n.id.toLowerCase().includes(ql) || n.name.toLowerCase().includes(ql),
  )
    .slice(0, 10)
    .map((n, i) => ({
      id: n.id,
      name: n.name,
      snippet: `${n.kind} in ${n.file}`,
      score: 1 - i * 0.07,
    }));
  return { hits };
}

/**
 * Mocked neighbors endpoint. Mirrors the PRD §12.3 contract:
 *
 *   GET /api/neighbors/:id?depth=N&cluster=auto
 *     → { center, cluster_level, nodes, edges, total_raw_nodes }
 *
 * The mock has a tiny dataset (~10 nodes), so clustering rarely kicks in —
 * but `cluster=module` always returns module-level aggregation so the UI can
 * be exercised end-to-end against mocks. `cluster=auto` picks "module" when
 * the raw set exceeds the same 500-node threshold the daemon will use.
 */
export function mockNeighbors(id: NodeId, opts: NeighborsQuery = {}): NeighborsResponse {
  const mode: ClusterMode = opts.cluster ?? "auto";
  const scope = opts.scope?.trim();

  // 1-hop neighbors of `id`, or whole graph for "*" / unknown.
  let rawIds: Set<string>;
  if (!NAMES.some((n) => n.id === id)) {
    rawIds = new Set(NAMES.map((n) => n.id));
  } else {
    rawIds = new Set([id]);
    for (const [src, dst] of EDGES) {
      if (src === id) rawIds.add(dst);
      if (dst === id) rawIds.add(src);
    }
  }
  // If a module scope is set, restrict to ids with that prefix.
  if (scope) {
    for (const nid of [...rawIds]) {
      if (!nid.startsWith(scope + "/") && nid !== scope) rawIds.delete(nid);
    }
  }
  const totalRaw = rawIds.size;

  const wantModule = mode === "module" || (mode === "auto" && totalRaw > 500);
  if (wantModule) {
    return buildModuleCluster(id, rawIds, totalRaw);
  }

  const nodes: GraphNode[] = [...rawIds].map((nid) => {
    const m = NAMES.find((n) => n.id === nid)!;
    return { id: m.id, name: m.name, kind: m.kind, file: m.file };
  });
  const edges: GraphEdge[] = EDGES.filter(([s, d]) => rawIds.has(s) && rawIds.has(d)).map(
    ([src, dst, kind, weight]) => ({ src, dst, kind, weight }),
  );
  return {
    center: id,
    cluster_level: "function",
    nodes,
    edges,
    total_raw_nodes: totalRaw,
  };
}

/**
 * Group nodes by directory prefix (everything before the last "/"). Within
 * the mock dataset this produces clusters like "auth", "db", "mail", "util",
 * "api". Each cluster carries a `count` of underlying functions; edges
 * between clusters are summed weights.
 */
function buildModuleCluster(
  center: NodeId,
  rawIds: Set<string>,
  totalRaw: number,
): NeighborsResponse {
  const prefixOf = (nid: string): string => {
    const ix = nid.lastIndexOf("/");
    return ix === -1 ? nid : nid.slice(0, ix);
  };
  const memberOf = new Map<string, string>();
  const counts = new Map<string, number>();
  for (const nid of rawIds) {
    const p = prefixOf(nid);
    memberOf.set(nid, p);
    counts.set(p, (counts.get(p) ?? 0) + 1);
  }
  const nodes: GraphNode[] = [...counts.entries()].map(([p, count]) => ({
    id: p,
    name: p,
    kind: "module",
    file: p,
    count,
  }));
  // Aggregate edges between modules (drop intra-module edges).
  const edgeWeights = new Map<string, number>();
  for (const [src, dst, , w] of EDGES) {
    if (!rawIds.has(src) || !rawIds.has(dst)) continue;
    const a = memberOf.get(src)!;
    const b = memberOf.get(dst)!;
    if (a === b) continue;
    const k = a + " " + b;
    edgeWeights.set(k, (edgeWeights.get(k) ?? 0) + w);
  }
  const edges: GraphEdge[] = [...edgeWeights.entries()].map(([k, weight]) => {
    const [src, dst] = k.split(" ") as [string, string];
    return { src, dst, kind: "cluster", weight };
  });
  return {
    center,
    cluster_level: "module",
    nodes,
    edges,
    total_raw_nodes: totalRaw,
  };
}

export function mockClaims(): ClaimsResponse {
  const claims: Claim[] = [
    {
      id: "claim_a4f7e2",
      agent: "agent_3",
      scope: ["auth/login_handler", "auth/validate_session", "auth/hash_password"],
      intent: "Adding rate limiting to login flow",
      created: new Date(Date.now() - 1_800_000).toISOString(),
      ttl: new Date(Date.now() + 1_800_000).toISOString(),
    },
  ];
  return { claims };
}

// Re-export the seed for tests and the /graph page's SSG fallback.
export const seedNames = NAMES;
export const seedEdges = EDGES;
